version: "3"

services:

  namenode:
    image: bde2020/hadoop-namenode:1.2.1-hadoop2.8.1-java8
    container_name: namenode
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    ports:
      - "50070:50070"
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env

  datanode:
    image: bde2020/hadoop-datanode:1.2.1-hadoop2.8.1-java8
    container_name: datanode
    volumes:
      - ./data/datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    depends_on:
      - namenode

  hive-server:
    image: zagrebaev/hadoop-hive:2.2.0-hadoop2.8.1-java8
    container_name: hive-server
    env_file:
      - ./hadoop-hive.env
    environment:
      - "HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore/metastore"
    ports:
      - "10000:10000"
    depends_on:
      - namenode
      - hive-metastore

  hive-metastore:
    image: zagrebaev/hadoop-hive:2.2.0-hadoop2.8.1-java8
    hostname: hive-metastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    depends_on:
      - hive-metastore-postgresql

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.2.0-hadoop2.8.1-java8
    hostname: hive-metastore-postgresql
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

  presto-coordinator:
    image: shawnzhu/prestodb:0.181
    container_name: presto-coordinator
    ports:
      - "8080:8080"
      
